# This file must be in your GitHub repository workflows dir.
# e.g. .github/workflows/release.yml

name: Upload to PyPI

# This action will be triggered when you create a new GitHub tag
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pypi-github-sync
      uses: PabloLec/pypi-github-sync@v1.0.1
      with:
          github_repo: PabloLec/recoverpy # Change these values
          twine_username: ${{ secrets.TWINE_USERNAME }}
          twine_password: ${{ secrets.TWINE_PASSWORD }}
          verify_metadata: true
          skip_existing: true
          verbose: true
